version: 2
jobs:
  php704_test:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install -y libgmp-dev re2c libmhash-dev libmcrypt-dev file
      - run: sudo docker-php-ext-configure gmp
      - run: sudo docker-php-ext-install gmp
      - run: composer install --no-interaction --ignore-platform-reqs
      - run: ./bin/phpcs
      - run: ./bin/phpunit
  php800_test:
    docker:
      - image: circleci/php:8.0
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install -y libgmp-dev re2c libmhash-dev libmcrypt-dev file
      - run: sudo docker-php-ext-configure gmp
      - run: sudo docker-php-ext-install gmp
      - run: composer install --no-interaction --ignore-platform-reqs
      - run: ./bin/phpcs
      - run: ./bin/phpunit

workflows:
  version: 2
  php704_test:
    jobs:
      - php704_test
  php800_test:
    jobs:
      - php800_test
